In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 로드
ori_df = pd.read_csv('./data/2016.csv', encoding='euc-kr')

In [3]:
ori_df.head(9)

   구분  죄종 발생검거      건수
0  중부  살인   발생     2.0
1  중부  살인   검거     2.0
2  중부  강도   발생     3.0
3  중부  강도   검거     3.0
4  중부  강간   발생   141.0
5  중부  강간   검거    96.0
6  중부  절도   발생  1204.0
7  중부  절도   검거   485.0
8  중부  폭력   발생  1335.0

In [4]:
# 피벗 테이블을 활용하여 데이터를 재구성한다.
tmp_df = pd.pivot_table(ori_df, 
                        columns=['죄종'],
                        index=['구분'], 
                        values=['건수'])

In [5]:
tmp_df.head(3)

       건수
죄종     강간    강도   살인      절도      폭력
구분
강남  304.0  25.0  3.0  1783.5  2216.0
강동  156.0  13.5  4.5  1328.0  2365.5
강북  188.0   4.5  6.5   947.0  2630.0

In [6]:
tmp_df
# 발생 검거가 기본 합산 후 평균으로 바뀌어서 원하는 형태가 되지 않았다.
# 발생과 검거는 데이터의 성격이 다르다.

        건수
죄종      강간    강도    살인      절도      폭력
구분
강남   304.0  25.0   3.0  1783.5  2216.0
강동   156.0  13.5   4.5  1328.0  2365.5
강북   188.0   4.5   6.5   947.0  2630.0
강서   257.0  10.0   9.5  1511.0  2986.0
관악   293.0  11.0   6.5  1520.0  2971.0
광진   256.5   8.5   4.0  1846.5  2201.5
구로   227.0  11.5   9.0  1385.5  2922.0
금천   159.0   7.0   6.0   959.0  2069.5
남대문   54.5   4.5   1.0   687.5   861.0
노원   150.5   7.5   5.5  1298.5  2320.0
도봉   122.0   5.0   3.0   679.0  1375.0
동대문  174.0  11.0   5.0  1505.5  2509.5
동작   237.0   7.0   7.0   890.0  1552.5
마포   359.5   5.5   4.0  1733.5  2719.5
방배    64.5   4.5   1.0   382.5   473.0
서대문  161.0   4.5   6.5  1127.5  1810.0
서부    51.5   3.0   4.0   585.0  1054.0
서초   285.0   7.0   4.0  1273.5  1710.5
성동    91.0   4.0   4.5  1096.0  1513.5
성북    89.0   3.0   2.0   585.5  1090.0
송파   209.0  13.5   8.5  1795.5  3048.5
수서   160.5  15.5   2.0   969.0  1548.5
양천   119.5   7.0   5.0  1237.0  2084.0
영등포  290.5  16.5  13.0  1640.5  3300.0
용산   232.5   9.5   4.0  1044.0  2196.0
은평    97.5   5.0   2.0   693.0  1432.0
종로   125.0   4.5   2.0   670.5  1213.0
종암    46.5   5.0   1.5   512.0   873.5
중랑   157.0  14.0   7.5  1371.5  2938.0
중부   118.5   3.0   2.0   844.5  1249.5
혜화    82.5   6.0   2.0   683.5   907.0

In [7]:
# 발생 검거 라는 컬럼의 데이터가 발생인놈만 모아서 사본을 받아서 피벗처리
df1 = ori_df[ori_df['발생검거']== '발생']
tmp_df1 = pd.pivot_table(df1, 
              index=['구분'],
              columns=['죄종'],
              values=['건수'])
newCol = {
    '강도':'강도발생',
    '살인':'살인발생',
    '절도':'절도발생',
    '폭력':'폭력발생'
}
tmp_df1.rename(columns=newCol, inplace=True)
tmp_df1.head(10)

        건수
죄종      강간  강도발생 살인발생    절도발생    폭력발생
구분
강남   339.0  24.0  3.0  2438.0  2336.0
강동   160.0  14.0  4.0  1754.0  2530.0
강북   217.0   5.0  7.0  1222.0  2778.0
강서   275.0  10.0  9.0  1952.0  3204.0
관악   322.0  12.0  6.0  2103.0  3235.0
광진   279.0  11.0  4.0  2636.0  2392.0
구로   273.0  10.0  9.0  1910.0  3164.0
금천   175.0   7.0  6.0  1264.0  2193.0
남대문   57.0   5.0  1.0   946.0   890.0
노원   159.0   6.0  5.0  1857.0  2516.0

In [8]:
# 발생 검거 라는 컬럼의 데이터가 검거인놈만 모아서 사본을 받아서 피벗처리
df2 = ori_df[ori_df['발생검거']== '검거']
tmp_df2 = pd.pivot_table(df2, 
              index=['구분'],
              columns=['죄종'],
              values=['건수'])
# newCol = {
#     '강간':'강간검거',
#     '강도':'강도검거',
#     '살인':'살인검거',
#     '절도':'절도검거',
#     '폭력':'폭력검거'
# }
# tmp_df2.rename(columns=newCol, inplace=True)
tmp_df2.head(10)

        건수
죄종      강간    강도    살인      절도      폭력
구분
강남   269.0  26.0   3.0  1129.0  2096.0
강동   152.0  13.0   5.0   902.0  2201.0
강북   159.0   4.0   6.0   672.0  2482.0
강서   239.0  10.0  10.0  1070.0  2768.0
관악   264.0  10.0   7.0   937.0  2707.0
광진   234.0   6.0   4.0  1057.0  2011.0
구로   181.0  13.0   9.0   861.0  2680.0
금천   143.0   7.0   6.0   654.0  1946.0
남대문   52.0   4.0   1.0   429.0   832.0
노원   142.0   9.0   6.0   740.0  2124.0

In [9]:
# 데이터 병합(tmp_df1, tmp_df2 병합을 한다.
# 행방향으로 병합
pd.merge(tmp_df1, tmp_df2, on='구분')
# 두개의 데이터가 같은 형태(shape)을 가지고 있다.
tmp = pd.concat([tmp_df1, tmp_df2], axis=1)
tmp

        건수
죄종      강간  강도발생  살인발생    절도발생    폭력발생     강간    강도    살인      절도      폭력
구분
강남   339.0  24.0   3.0  2438.0  2336.0  269.0  26.0   3.0  1129.0  2096.0
강동   160.0  14.0   4.0  1754.0  2530.0  152.0  13.0   5.0   902.0  2201.0
강북   217.0   5.0   7.0  1222.0  2778.0  159.0   4.0   6.0   672.0  2482.0
강서   275.0  10.0   9.0  1952.0  3204.0  239.0  10.0  10.0  1070.0  2768.0
관악   322.0  12.0   6.0  2103.0  3235.0  264.0  10.0   7.0   937.0  2707.0
광진   279.0  11.0   4.0  2636.0  2392.0  234.0   6.0   4.0  1057.0  2011.0
구로   273.0  10.0   9.0  1910.0  3164.0  181.0  13.0   9.0   861.0  2680.0
금천   175.0   7.0   6.0  1264.0  2193.0  143.0   7.0   6.0   654.0  1946.0
남대문   57.0   5.0   1.0   946.0   890.0   52.0   4.0   1.0   429.0   832.0
노원   159.0   6.0   5.0  1857.0  2516.0  142.0   9.0   6.0   740.0  2124.0
도봉   123.0   5.0   3.0   866.0  1441.0  121.0   5.0   3.0   492.0  1309.0
동대문  190.0  10.0   5.0  1940.0  2642.0  158.0  12.0   5.0  1071.0  2377.0
동작   325.0   7.0   8.0  1226.0  1661.0  149.0   7.0   6.0   554.0  1444.0
마포   399.0   4.0   4.0  2527.0  2939.0  320.0   7.0   4.0   940.0  2500.0
방배    78.0   4.0   1.0   472.0   500.0   51.0   5.0   1.0   293.0   446.0
서대문  175.0   5.0   6.0  1503.0  1976.0  147.0   4.0   7.0   752.0  1644.0
서부    54.0   4.0   4.0   781.0  1128.0   49.0   2.0   4.0   389.0   980.0
서초   350.0   9.0   4.0  1733.0  1838.0  220.0   5.0   4.0   814.0  1583.0
성동   104.0   3.0   4.0  1296.0  1619.0   78.0   5.0   5.0   896.0  1408.0
성북   103.0   3.0   2.0   790.0  1176.0   75.0   3.0   2.0   381.0  1004.0
송파   234.0  15.0   9.0  2543.0  3289.0  184.0  12.0   8.0  1048.0  2808.0
수서   177.0  15.0   2.0  1149.0  1666.0  144.0  16.0   2.0   789.0  1431.0
양천   131.0   7.0   5.0  1719.0  2250.0  108.0   7.0   5.0   755.0  1918.0
영등포  356.0  19.0  13.0  2341.0  3593.0  225.0  14.0  13.0   940.0  3007.0
용산   251.0   9.0   4.0  1489.0  2384.0  214.0  10.0   4.0   599.0  2008.0
은평   102.0   5.0   2.0   885.0  1536.0   93.0   5.0   2.0   501.0  1328.0
종로   137.0   6.0   4.0   952.0  1291.0  113.0   3.0   0.0   389.0  1135.0
종암    51.0   5.0   2.0   680.0   932.0   42.0   5.0   1.0   344.0   815.0
중랑   164.0  14.0   8.0  1691.0  3164.0  150.0  14.0   7.0  1052.0  2712.0
중부   141.0   3.0   2.0  1204.0  1335.0   96.0   3.0   2.0   485.0  1164.0
혜화   101.0   6.0   2.0   988.0   972.0   64.0   6.0   2.0   379.0   842.0

In [10]:
# pandas 데이터프레임의 값 파트 변경작업
tmp = tmp.astype(np.int)
tmp

      건수
죄종    강간 강도발생 살인발생  절도발생  폭력발생   강간  강도  살인    절도    폭력
구분
강남   339   24    3  2438  2336  269  26   3  1129  2096
강동   160   14    4  1754  2530  152  13   5   902  2201
강북   217    5    7  1222  2778  159   4   6   672  2482
강서   275   10    9  1952  3204  239  10  10  1070  2768
관악   322   12    6  2103  3235  264  10   7   937  2707
광진   279   11    4  2636  2392  234   6   4  1057  2011
구로   273   10    9  1910  3164  181  13   9   861  2680
금천   175    7    6  1264  2193  143   7   6   654  1946
남대문   57    5    1   946   890   52   4   1   429   832
노원   159    6    5  1857  2516  142   9   6   740  2124
도봉   123    5    3   866  1441  121   5   3   492  1309
동대문  190   10    5  1940  2642  158  12   5  1071  2377
동작   325    7    8  1226  1661  149   7   6   554  1444
마포   399    4    4  2527  2939  320   7   4   940  2500
방배    78    4    1   472   500   51   5   1   293   446
서대문  175    5    6  1503  1976  147   4   7   752  1644
서부    54    4    4   781  1128   49   2   4   389   980
서초   350    9    4  1733  1838  220   5   4   814  1583
성동   104    3    4  1296  1619   78   5   5   896  1408
성북   103    3    2   790  1176   75   3   2   381  1004
송파   234   15    9  2543  3289  184  12   8  1048  2808
수서   177   15    2  1149  1666  144  16   2   789  1431
양천   131    7    5  1719  2250  108   7   5   755  1918
영등포  356   19   13  2341  3593  225  14  13   940  3007
용산   251    9    4  1489  2384  214  10   4   599  2008
은평   102    5    2   885  1536   93   5   2   501  1328
종로   137    6    4   952  1291  113   3   0   389  1135
종암    51    5    2   680   932   42   5   1   344   815
중랑   164   14    8  1691  3164  150  14   7  1052  2712
중부   141    3    2  1204  1335   96   3   2   485  1164
혜화   101    6    2   988   972   64   6   2   379   842

In [11]:
#컬럼명 변경
#병합전에 수정 처리
newCol = {
    '강간':'강간검거',
    '강도':'강도검거',
    '살인':'살인검거',
    '절도':'절도검거',
    '폭력':'폭력검거'
}
tmp.rename(columns=newCol,inplace=True)

In [12]:
tmp.to_csv('./data/2016_start.csv', sep = ',' , encoding = 'euc-kr') # 최초가 euc-kr이다보니 저장 와중에 깨질수가 있다.

In [23]:
# 특정 행부터 데이터를 가져온다.
crime_per_police = pd.read_csv('./data/2016_start.csv', encoding = 'euc-kr', header=1)
crime_per_police.head(3)
#열 떨구기 del, 행 떨구기 drop (근데 방향 조정 가능)
crime_per_police.drop(axis = 1, index = [0], inplace=True)

In [24]:
# 특정 칼럼을 인덱스로 설정
crime_per_police.set_index('죄종', inplace = True)
crime_per_police.head(2)

     강간검거  강도발생  살인발생    절도발생    폭력발생  강간검거.1  강도검거  살인검거    절도검거    폭력검거
죄종
강남  339.0  24.0   3.0  2438.0  2336.0   269.0  26.0   3.0  1129.0  2096.0
강동  160.0  14.0   4.0  1754.0  2530.0   152.0  13.0   5.0   902.0  2201.0

In [59]:
# 타입 보정
crime_per_police.astype(np.int32, inplace = True)

     강간검거  강도발생  살인발생  절도발생  폭력발생  강간검거.1  강도검거  살인검거  절도검거  폭력검거
죄종
강남    339    24     3  2438  2336     269    26     3  1129  2096
강동    160    14     4  1754  2530     152    13     5   902  2201
강북    217     5     7  1222  2778     159     4     6   672  2482
강서    275    10     9  1952  3204     239    10    10  1070  2768
관악    322    12     6  2103  3235     264    10     7   937  2707
광진    279    11     4  2636  2392     234     6     4  1057  2011
구로    273    10     9  1910  3164     181    13     9   861  2680
금천    175     7     6  1264  2193     143     7     6   654  1946
남대문    57     5     1   946   890      52     4     1   429   832
노원    159     6     5  1857  2516     142     9     6   740  2124
도봉    123     5     3   866  1441     121     5     3   492  1309
동대문   190    10     5  1940  2642     158    12     5  1071  2377
동작    325     7     8  1226  1661     149     7     6   554  1444
마포    399     4     4  2527  2939     320     7     4   940  2500
방배     78     4     1   472   500      51     5     1   293   446
서대문   175     5     6  1503  1976     147     4     7   752  1644
서부     54     4     4   781  1128      49     2     4   389   980
서초    350     9     4  1733  1838     220     5     4   814  1583
성동    104     3     4  1296  1619      78     5     5   896  1408
성북    103     3     2   790  1176      75     3     2   381  1004
송파    234    15     9  2543  3289     184    12     8  1048  2808
수서    177    15     2  1149  1666     144    16     2   789  1431
양천    131     7     5  1719  2250     108     7     5   755  1918
영등포   356    19    13  2341  3593     225    14    13   940  3007
용산    251     9     4  1489  2384     214    10     4   599  2008
은평    102     5     2   885  1536      93     5     2   501  1328
종로    137     6     4   952  1291     113     3     0   389  1135
종암     51     5     2   680   932      42     5     1   344   815
중랑    164    14     8  1691  3164     150    14     7  1052  2712
중부    141     3     2  1204  1335      96     3     2   485  1164
혜화    101     6     2   988   972      64     6     2   379   842

In [25]:
# 주소 (-) gps 값, 지형지물명(-) 주소 및 위치정보 획득 : 지오코더(geocoder)
# kakao API 사용 => 계정 등록 => 앱생성 => 인증키 발급(restful key)
# dev.kakao.com

# 저장의 형태를 좀 더 조정하거나, 아니면 데이터를 읽을 때 조정하거나 해서 2015와 같은 형식 필요

In [15]:
# API를 이용한 http 통신을 통해서 획득
# requests, urllib,beautifulsoup, selenium 등등이 웹 크롤링 기술 대상 모듈
import requests
url = '''https://dapi.kakao.com/v2/local/search/keyword.json?query={0}&category_group_code=PO3
'''.format('서울 중부 경찰서')
KAKAO_API_KEY = 'f9bcade751569c67742c3c82a2e2f2af'
headers = {
    'Authorization':'KakaoAK {0}'.format(KAKAO_API_KEY)
}
res = requests.get(url, headers=headers)

In [16]:
res = res.json()
res

{'documents': [{'address_name': '서울 중구 저동2가 62-1',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서',
   'distance': '',
   'id': '11151738',
   'phone': '182',
   'place_name': '서울중부경찰서',
   'place_url': 'http://place.map.daum.net/11151738',
   'road_address_name': '서울 중구 수표로 27',
   'x': '126.98959193048435',
   'y': '37.563620722687844'},
  {'address_name': '서울 중구 을지로3가 291-50',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 파출소',
   'distance': '',
   'id': '21268201',
   'phone': '02-2266-2404',
   'place_name': '서울중부경찰서 을지로3가파출소',
   'place_url': 'http://place.map.daum.net/21268201',
   'road_address_name': '서울 중구 충무로 56-1',
   'x': '126.99286493571154',
   'y': '37.56620864804315'},
  {'address_name': '서울 중구 을지로5가 72-1',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 지구대',
   'distance': '',
   'id': '8528186',
   'phone': '02-2279-1908',
   'place_name': '서울중부경찰서 을지지구대',
   'place_url': 'http://place.map.daum.net/8528186',
   'road_address_name': '서울 중구 을지로 234',
   'x': '127.00393932989843',
   'y': '37.56650806865062'},
  {'address_name': '서울 중구 장충동2가 197-34',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 파출소',
   'distance': '',
   'id': '8050461',
   'phone': '',
   'place_name': '서울중부경찰서 장충파출소',
   'place_url': 'http://place.map.daum.net/8050461',
   'road_address_name': '서울 중구 동호로 261',
   'x': '127.00480828177658',
   'y': '37.55875233220571'},
  {'address_name': '서울 중구 약수동 844-3',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 지구대',
   'distance': '',
   'id': '9111102',
   'phone': '02-2234-8112',
   'place_name': '서울중부경찰서 약수지구대',
   'place_url': 'http://place.map.daum.net/9111102',
   'road_address_name': '서울 중구 동호로5길 15',
   'x': '127.0123811614773',
   'y': '37.55217464886805'},
  {'address_name': '서울 중구 신당동 100-1',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 파출소',
   'distance': '',
   'id': '21268204',
   'phone': '',
   'place_name': '서울중부경찰서 신당파출소',
   'place_url': 'http://place.map.daum.net/21268204',
   'road_address_name': '서울 중구 다산로 248',
   'x': '127.01638984949119',
   'y': '37.565051159146165'},
  {'address_name': '서울 중구 신당동 250-10',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서 > 지구대',
   'distance': '',
   'id': '10487492',
   'phone': '',
   'place_name': '서울중부경찰서 광희지구대',
   'place_url': 'http://place.map.daum.net/10487492',
   'road_address_name': '서울 중구 퇴계로 375-1',
   'x': '127.01340174502059',
   'y': '37.565249715229605'},
  {'address_name': '서울 중구 저동2가 62-1',
   'category_group_code': 'PO3',
   'category_group_name': '공공기관',
   'category_name': '사회,공공기관 > 행정기관 > 경찰서',
   'distance': '',
   'id': '10795753',
   'phone': '',
   'place_name': '중부경찰서 민원봉사실',
   'place_url': 'http://place.map.daum.net/10795753',
   'road_address_name': '서울 중구 수표로 27',
   'x': '126.99002655182646',
   'y': '37.563674825136786'}],
 'meta': {'is_end': True,
  'pageable_count': 8,
  'same_name': {'keyword': '서울 중부 경찰서', 'region': [], 'selected_region': ''},
  'total_count': 8}}

In [17]:
res['documents'][0]

{'address_name': '서울 중구 저동2가 62-1',
 'category_group_code': 'PO3',
 'category_group_name': '공공기관',
 'category_name': '사회,공공기관 > 행정기관 > 경찰서',
 'distance': '',
 'id': '11151738',
 'phone': '182',
 'place_name': '서울중부경찰서',
 'place_url': 'http://place.map.daum.net/11151738',
 'road_address_name': '서울 중구 수표로 27',
 'x': '126.98959193048435',
 'y': '37.563620722687844'}

In [18]:
print(res['documents'][0]['address_name'],
res['documents'][0]['y'],
res['documents'][0]['x'],
res['documents'][0]['place_name'])

서울 중구 저동2가 62-1 37.563620722687844 126.98959193048435 서울중부경찰서

### 범죄 통계 데이터에서 관할서에 대한 정보 추출
- 반복작업을 통해 kakao API를 활용하여 주소,위도,경도등 획득

In [27]:
# 반복해서 관할서의 이름을 완성하여 출력(print)하시오.
crime_per_police.index

Index(['강남', '강동', '강북', '강서', '관악', '광진', '구로', '금천', '남대문', '노원', '도봉',
       '동대문', '동작', '마포', '방배', '서대문', '서부', '서초', '성동', '성북', '송파', '수서',
       '양천', '영등포', '용산', '은평', '종로', '종암', '중랑', '중부', '혜화'],
      dtype='object', name='죄종')

In [34]:
# 검색어를 던져서 응답 데이터중에 주소, 위도, 경도, 질의어 리턴 함수
def netGetGeocoder(query):    
    url = '''https://dapi.kakao.com/v2/local/search/keyword.json?query={0}&category_group_code=PO3
    '''.format(query)
    KAKAO_API_KEY = 'f9bcade751569c67742c3c82a2e2f2af'
    headers = {
        'Authorization':'KakaoAK {0}'.format(KAKAO_API_KEY)
    }    
    #API 쿼리 수행
    res = requests.get(url, headers=headers)
    res = res.json()
    # 데이터 추출 : 주소, 위도, 경도, 질의어 순으로 튜플 형태로 리턴
    return res['documents'][0]['address_name'],res['documents'][0]['y'],res['documents'][0]['x'],res['documents'][0]['place_name']

In [37]:
# 반복해서 관할서의 이름을 완성하여 출력(print)하시오.
# 진행율
from tqdm import tqdm_notebook

#데이터를 담는 자료형

police_station_info = []

#경찰서 이름 개수만큼 반복
for name in tqdm_notebook(crime_per_police.index):
    #검색어 획득
    query  = '서울 %s 경찰서'%name
    
    police_station_info.append(netGetGeocoder(query))

HBox(children=(IntProgress(value=0, max=31), HTML(value='')))

In [63]:
print(police_station_info)

[('서울 강남구 대치동 998', '37.50938856957773', '127.06707150521913', '서울강남경찰서'), ('서울 강동구 성내동 541-1', '37.528675586086614', '127.12689445192979', '서울강동경찰서'), ('서울 강북구 번동 415-15', '37.63740904254407', '127.02733964805316', '강북경찰서'), ('서울 양천구 신월동 25', '37.539782668110185', '126.82998362436423', '서울강서경찰서 임시청사'), ('서울 관악구 봉천동 1695-5', '37.474588550832955', '126.95106042259249', '서울관악경찰서'), ('서울 광진구 구의동 254-32', '37.5428121811901', '127.08384292223185', '서울광진경찰서'), ('서울 구로구 구로동 436', '37.49488449504183', '126.8866584714525', '서울구로경찰서'), ('서울 관악구 신림동 544', '37.48141868421242', '126.9099695798393', '서울금천경찰서'), ('서울 중구 남대문로5가 561', '37.55497931115527', '126.97350028716411', '서울남대문경찰서'), ('서울 노원구 하계동 250', '37.6423345266253', '127.071404832413', '서울노원경찰서'), ('서울 도봉구 창동 17', '37.65339850283973', '127.05270640425917', '서울도봉경찰서'), ('서울 동대문구 청량리동 229', '37.58508176321097', '127.04576239696928', '서울동대문경찰서'), ('서울 동작구 노량진동 72-35', '37.513147550556226', '126.94285899341229', '서울동작경찰서'), ('서울 마포구 아현동 618-1', '37.55101229580099', '126.95394220726662', '서울마포경찰서'), ('서울 서초구 방배동 455-10', '37.48155944749938', '126.98300906928465', '서울방배경찰서(2022년예정)'), ('서울 서대문구 미근동 165', '37.56490283018693', '126.96679138866718', '서울서대문경찰서'), ('서울 은평구 대조동 2-9', '37.61288240068257', '126.92747714311908', '서울서부경찰서'), ('서울 서초구 서초동 1726-1', '37.495614213519424', '127.00528950116143', '서초경찰서'), ('서울 성동구 행당동 192-8', '37.561796153278124', '127.03647222445021', '서울성동경찰서'), ('서울 성북구 삼선동5가 301', '37.58977065462821', '127.01625436761046', '서울성북경찰서'), ('서울 송파구 가락동 9', '37.501976988845826', '127.12716193066983', '서울송파경찰서'), ('서울 강남구 개포동 14', '37.49349614550641', '127.07714424999398', '수서경찰서'), ('서울 양천구 신정동 321', '37.51655448877979', '126.86554089186782', '서울양천경찰서'), ('서울 영등포구 당산동3가 2-11', '37.52585217071908', '126.90094655076123', '서울영등포경찰서'), ('서울 용산구 원효로1가 12-12', '37.5411811395942', '126.967778896191', '서울용산경찰서'), ('서울 은평구 불광동 산 24', '37.62852372694348', '126.92863070648912', '서울은평경찰서'), ('서울 종로구 경운동 90-18', '37.57554203072626', '126.98489890358965', '서울종로경찰서'), ('서울 성북구 종암동 3-1260', '37.60209664507542', '127.0322331298805', '서울종암경찰서'), ('서울 중랑구 신내동 810', '37.618237310628686', '127.10454069232486', '서울중랑경찰서'), ('서울 중구 저동2가 62-1', '37.563620722687844', '126.98959193048435', '서울중부경찰서'), ('서울 종로구 인의동 48-57', '37.57189237089298', '126.99893618246821', '서울혜화경찰서')]

In [57]:
# 위도만 추출해서 리스트로 출력 -> df에 컬럼 삽입을 해야하므로
#리스트 내포
# addrs, lats , lngs, names, 
addrs = [element[0] for element in police_station_info]
lats = [element[1] for element in police_station_info]
lngs = [element[2] for element in police_station_info]
names = [element[3] for element in police_station_info]

In [60]:
crime_per_police.head(2)

     강간검거  강도발생  살인발생    절도발생    폭력발생  강간검거.1  강도검거  살인검거    절도검거    폭력검거
죄종
강남  339.0  24.0   3.0  2438.0  2336.0   269.0  26.0   3.0  1129.0  2096.0
강동  160.0  14.0   4.0  1754.0  2530.0   152.0  13.0   5.0   902.0  2201.0

In [68]:
# crime_per_police 정보에 자치구 정보가 없다. -> 자치구: XX구 데이터 추가 필요
# addrs -> 구를 획득 ->칼럼 추가.
# 
# tmp_gu = []
# for addr in addrs:
#     # 분해 
#     tmp_gu.append(addr.split()[1]))# default blank
#     #print(addr.split(' ')[1])        
#리스트 내포
tmp_gu = [addr.split()[1] for addr in addrs if addr]

In [69]:
crime_per_police['자치구'] = tmp_gu

In [72]:
crime_per_police.head(2)

     강간검거  강도발생  살인발생    절도발생    폭력발생  강간검거.1  강도검거  살인검거    절도검거    폭력검거  자치구
죄종
강남  339.0  24.0   3.0  2438.0  2336.0   269.0  26.0   3.0  1129.0  2096.0  강남구
강동  160.0  14.0   4.0  1754.0  2530.0   152.0  13.0   5.0   902.0  2201.0  강동구

In [79]:
# 키 역할을 담당할 자치구 컬럼의 unique 조사
len(crime_per_police['자치구'].unique())
crime_per_police['자치구'].unique()
# 주소에서 자치구를 추출하다 보니 실제 소속 자치구와 일치하지 않는 관할서가 있다. 
# 금천구가 존재하지만 금천 -> 관악구, 금천구로 대체

23

In [98]:
# 금천 -> 관악구 =>금천구 대체, 수행

crime_per_police.loc[crime_per_police.index=='금천','자치구'] = '금천구'

        

# 강서 -> 양천구 => 강서구 대체
crime_per_police.loc[crime_per_police.index=='강서','자치구'] = '강서구'

In [97]:
crime_per_police

,강간검거,강도발생,살인발생,절도발생,폭력발생,강간검거.1,강도검거,살인검거,절도검거,폭력검거,자치구
죄종,,,,,,,,,,,
강남,339.0,24.0,3.0,2438.0,2336.0,269.0,26.0,3.0,1129.0,2096.0,강남구
강동,160.0,14.0,4.0,1754.0,2530.0,152.0,13.0,5.0,902.0,2201.0,강동구
강북,217.0,5.0,7.0,1222.0,2778.0,159.0,4.0,6.0,672.0,2482.0,강북구
강서,275.0,10.0,9.0,1952.0,3204.0,239.0,10.0,10.0,1070.0,2768.0,양천구
관악,322.0,12.0,6.0,2103.0,3235.0,264.0,10.0,7.0,937.0,2707.0,관악구
광진,279.0,11.0,4.0,2636.0,2392.0,234.0,6.0,4.0,1057.0,2011.0,광진구
구로,273.0,10.0,9.0,1910.0,3164.0,181.0,13.0,9.0,861.0,2680.0,구로구
금천,175.0,7.0,6.0,1264.0,2193.0,143.0,7.0,6.0,654.0,1946.0,금천구
남대문,57.0,5.0,1.0,946.0,890.0,52.0,4.0,1.0,429.0,832.0,중구
노원,159.0,6.0,5.0,1857.0,2516.0,142.0,9.0,6.0,740.0,2124.0,노원구
도봉,123.0,5.0,3.0,866.0,1441.0,121.0,5.0,3.0,492.0,1309.0,도봉구
동대문,190.0,10.0,5.0,1940.0,2642.0,158.0,12.0,5.0,1071.0,2377.0,동대문구
동작,325.0,7.0,8.0,1226.0,1661.0,149.0,7.0,6.0,554.0,1444.0,동작구
마포,399.0,4.0,4.0,2527.0,2939.0,320.0,7.0,4.0,940.0,2500.0,마포구
방배,78.0,4.0,1.0,472.0,500.0,51.0,5.0,1.0,293.0,446.0,서초구
서대문,175.0,5.0,6.0,1503.0,1976.0,147.0,4.0,7.0,752.0,1644.0,서대문구
서부,54.0,4.0,4.0,781.0,1128.0,49.0,2.0,4.0,389.0,980.0,은평구
서초,350.0,9.0,4.0,1733.0,1838.0,220.0,5.0,4.0,814.0,1583.0,서초구
성동,104.0,3.0,4.0,1296.0,1619.0,78.0,5.0,5.0,896.0,1408.0,성동구
성북,103.0,3.0,2.0,790.0,1176.0,75.0,3.0,2.0,381.0,1004.0,성북구
송파,234.0,15.0,9.0,2543.0,3289.0,184.0,12.0,8.0,1048.0,2808.0,송파구
수서,177.0,15.0,2.0,1149.0,1666.0,144.0,16.0,2.0,789.0,1431.0,강남구
양천,131.0,7.0,5.0,1719.0,2250.0,108.0,7.0,5.0,755.0,1918.0,양천구
영등포,356.0,19.0,13.0,2341.0,3593.0,225.0,14.0,13.0,940.0,3007.0,영등포구
용산,251.0,9.0,4.0,1489.0,2384.0,214.0,10.0,4.0,599.0,2008.0,용산구
은평,102.0,5.0,2.0,885.0,1536.0,93.0,5.0,2.0,501.0,1328.0,은평구
종로,137.0,6.0,4.0,952.0,1291.0,113.0,3.0,0.0,389.0,1135.0,종로구
종암,51.0,5.0,2.0,680.0,932.0,42.0,5.0,1.0,344.0,815.0,성북구
중랑,164.0,14.0,8.0,1691.0,3164.0,150.0,14.0,7.0,1052.0,2712.0,중랑구
중부,141.0,3.0,2.0,1204.0,1335.0,96.0,3.0,2.0,485.0,1164.0,중구
혜화,101.0,6.0,2.0,988.0,972.0,64.0,6.0,2.0,379.0,842.0,종로구

In [100]:
len(crime_per_police['자치구'].unique())

25

In [102]:
# 데이터저장(crime_analysis_mid_save.csv)
crime_per_police.to_csv('./data/crime_analysis_mid_save.csv', sep = ',')

### 피벗테이블 기능 학습